services:
  - type: web
    name: society-backend
    env: docker
    dockerfilePath: ./docker/backend.Dockerfile
    healthCheckPath: /api/v1/health
    envVars:
      - key: PORT
        value: 4000
