import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { LoggerModule } from 'nestjs-pino';
import { ThrottlerModule } from '@nestjs/throttler';
import { ClsModule } from 'nestjs-cls';
import { DatabaseModule } from '@core/database/database.module';
import { UserModule } from './modules/user/user.module';
import { AuthModule } from './modules/auth/auth.module';
import { v4 as uuidv4 } from 'uuid';
import { SocietyModule } from './modules/society/society.module';
import { FlatModule } from './modules/flat/flat.module';
import { MemberModule } from './modules/member/member.module';
import { MaintenanceModule } from './modules/maintenance/maintenance.module';
import { PaymentModule } from './modules/payment/payment.module';
import { AccountingModule } from './modules/accounting/accounting.module';
import { ResidentModule } from './modules/resident/resident.module';
import { ComplaintModule } from './modules/complaint/complaint.module';
import { AssetModule } from './modules/asset/asset.module';
import { ReportModule } from './modules/report/report.module';
import { NotificationModule } from './modules/notification/notification.module';
import { SuperAdminModule } from './modules/superadmin/superadmin.module';
import { AIModule } from './modules/ai/ai.module';
import { HealthModule } from './modules/health/health.module';
import { QueueModule } from './modules/queue/queue.module';
import { WorkerModule } from './modules/worker/worker.module';
import { AuditModule } from './core/audit/audit.module';

@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
      envFilePath: ['.env.local', '.env'],
    }),
    LoggerModule.forRoot({
      pinoHttp: {
        genReqId: (req: any) => req.id, // Use the ID generated by ClsModule
        transport: process.env.NODE_ENV !== 'production'
          ? { target: 'pino-pretty', options: { colorize: true, singleLine: true } }
          : undefined,
        autoLogging: false,
      },
    }),
    ThrottlerModule.forRoot([{
      ttl: 60000,
      limit: 100,
    }]),
    ClsModule.forRoot({
      global: true,
      middleware: {
        mount: true,
        generateId: true,
        idGenerator: (req: any) => req.headers['x-request-id'] || uuidv4(),
        setup: (cls, req: any) => {
          // Resolve and inject initial tenant id from request header x-tenant-id
          const tenantId = req.headers['x-tenant-id'] || null;
          cls.set('tenantId', tenantId);
        },
      },
    }),
    DatabaseModule,
    UserModule,
    AuthModule,
    SocietyModule,
    FlatModule,
    MemberModule,
    MaintenanceModule,
    PaymentModule,
    AccountingModule,
    ResidentModule,
    ComplaintModule,
    AssetModule,
    ReportModule,
    NotificationModule,
    SuperAdminModule,
    AIModule,
    HealthModule,
    QueueModule,
    WorkerModule,
    AuditModule,
  ],
  controllers: [],
  providers: [],
})
export class AppModule {}
